;;; esi-dictate-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from esi-dictate.el

(autoload 'esi-dictate-start "esi-dictate" "\
Start the real-time transcription process to start inserting text
in current buffer." t)
(register-definition-prefixes "esi-dictate" '("esi-dictate-"))


;;; Generated autoloads from esi-utils.el

(register-definition-prefixes "esi-utils" '("esi-utils-"))

;;; End of scraped data

(provide 'esi-dictate-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; esi-dictate-autoloads.el ends here
