[project]
name = "esi-dictate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.9"
dependencies = [
    "deepgram-sdk>=4.7.0",
    "openai>=1.97.1",
    "pyaudio>=0.2.14",
    "websockets>=15.0.1",
]
